DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
Paginate = 3
disqusShortname = "yourdiscussshortname"
SectionPagesMenu = "main"
baseURL = "https://altmavericks.github.io/repo/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "ananke"
title = "altMavericks"
[params]
background_color_class = "bg-black"
description = "The Best brains inTown"
facebook = ""
favicon = ""
featured_image = "/images/gohugo-default-sample-hero-image.jpg"
github = ""
instagram = ""
linkedin = ""
twitter = "https://twitter.com/GoHugoIO"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
