---
pages:
- post/infosec.md
- post/demo.md
- post/all-this-will-be-deleted.md
- post/test-1.md
- post/5.md
- post/4.md
- post/3.md
- post/test.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: text
  default: Author
  label: Author
  name: author
  description: Helps you add the Author name
  config:
    required: true
  hidden: false
